#!/usr/bin/env bash
# Generate docker-compose.yml with N teams.
# Usage: ./setup.sh [number_of_teams]
# Default: 4 teams

set -e

TEAMS=${1:-4}
NANTES_HACK=${VITE_NANTES_HACK:-1}

NAMES=(Alpha Bravo Charlie Delta Echo Foxtrot Golf Hotel India Juliet Kilo Lima Mike November Oscar Papa Quebec Romeo Sierra Tango)

if [ "$TEAMS" -lt 1 ] || [ "$TEAMS" -gt ${#NAMES[@]} ]; then
  echo "Nombre d'equipes entre 1 et ${#NAMES[@]}"
  exit 1
fi

FILE="docker-compose.yml"

cat > "$FILE" <<EOF
# Auto-generated by setup.sh — $TEAMS equipe(s)
# Toggle "0" / "1" pour activer le branding Nantes@Hack sur tous les services.
x-build-args: &build-args
  VITE_NANTES_HACK: "$NANTES_HACK"

services:
  # Central live dashboard (to project on screen)
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
      args: *build-args
    ports:
      - "5000:5000"
    restart: unless-stopped
EOF

for i in $(seq 1 "$TEAMS"); do
  NAME=${NAMES[$((i - 1))]}
  SITE_PORT=$((3000 + i))
  EXPLOIT_PORT=$((4000 + i))

  cat >> "$FILE" <<EOF

  # ──────────────────────── Team $i ────────────────────────
  site-team${i}:
    build:
      context: .
      dockerfile: Dockerfile.site
      args: *build-args
    environment:
      - TEAM_NAME=$NAME
      - DASHBOARD_URL=http://dashboard:5000
    ports:
      - "${SITE_PORT}:3000"
    depends_on:
      - dashboard
    restart: unless-stopped

  exploit-team${i}:
    build:
      context: .
      dockerfile: Dockerfile.exploit
      args: *build-args
    environment:
      - TEAM_NAME=$NAME
      - TEAM_PASSWORD=team${i}-banana
      - SITE_URL=http://site-team${i}:3000
      - DASHBOARD_URL=http://dashboard:5000
    ports:
      - "${EXPLOIT_PORT}:4000"
    restart: unless-stopped
EOF
done

echo ""
echo "docker-compose.yml genere avec $TEAMS equipe(s)."
echo ""
echo "  Dashboard:  http://localhost:5000"
for i in $(seq 1 "$TEAMS"); do
  echo "  Team $i:     http://localhost:$((3000 + i)) (site)  http://localhost:$((4000 + i)) (exploit)"
done
echo ""
echo "Lancez: docker compose up --build -d"
