#!/usr/bin/env bash
# Generate docker-compose.yml with N teams and optionally deploy.
# Usage: ./setup.sh [number_of_teams] [--deploy]
#   --deploy   Build & start containers after generating docker-compose.yml
#   --reset    Stop & remove containers, volumes, and generated files
# Default: 4 teams

set -e

# ─────────────────────────── Helpers ───────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

ok()   { printf "  ${GREEN}✔${NC} %s\n" "$1"; }
warn() { printf "  ${YELLOW}⚠${NC} %s\n" "$1"; }
fail() { printf "  ${RED}✖${NC} %s\n" "$1"; exit 1; }
info() { printf "  ${CYAN}ℹ${NC} %s\n" "$1"; }

# ─────────────────────────── Parse args ───────────────────────────

TEAMS=4
DEPLOY=false
RESET=false

for arg in "$@"; do
  case "$arg" in
    --deploy) DEPLOY=true ;;
    --reset)  RESET=true ;;
    [0-9]*)   TEAMS="$arg" ;;
  esac
done

NANTES_HACK=${VITE_NANTES_HACK:-1}
NAMES=(Alpha Bravo Charlie Delta Echo Foxtrot Golf Hotel India Juliet Kilo Lima Mike November Oscar Papa Quebec Romeo Sierra Tango)

# ─────────────────────────── Reset mode ───────────────────────────

if $RESET; then
  echo ""
  echo "🧹 Reset de l'environnement CTF..."
  echo ""
  if command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
    if [ -f "docker-compose.yml" ]; then
      docker compose down -v --remove-orphans 2>/dev/null && ok "Conteneurs et volumes supprimés" || warn "Aucun conteneur à arrêter"
    fi
  fi
  rm -f docker-compose.yml && ok "docker-compose.yml supprimé" || true
  rm -f credentials.json credentials.html && ok "Fichiers d'identifiants supprimés" || true
  echo ""
  ok "Reset terminé."
  echo ""
  exit 0
fi

# ─────────────────────────── Prerequisites ───────────────────────────

echo ""
echo "🔍 Vérification des prérequis..."
echo ""

# Docker
if ! command -v docker &>/dev/null; then
  fail "Docker n'est pas installé. Installez-le: https://docs.docker.com/engine/install/"
fi
ok "Docker trouvé ($(docker --version | head -c 50))"

# Docker daemon
if ! docker info &>/dev/null 2>&1; then
  fail "Le daemon Docker ne tourne pas. Lancez: sudo systemctl start docker"
fi
ok "Daemon Docker actif"

# Docker Compose
if ! docker compose version &>/dev/null 2>&1; then
  fail "Docker Compose plugin manquant. Installez-le: https://docs.docker.com/compose/install/"
fi
ok "Docker Compose trouvé ($(docker compose version --short 2>/dev/null))"

# RAM check (recommend 512MB per team minimum)
TOTAL_RAM_MB=$(free -m 2>/dev/null | awk '/Mem:/{print $2}' || echo 0)
REQUIRED_RAM_MB=$(( TEAMS * 512 ))
if [ "$TOTAL_RAM_MB" -gt 0 ]; then
  if [ "$TOTAL_RAM_MB" -lt "$REQUIRED_RAM_MB" ]; then
    warn "RAM disponible: ${TOTAL_RAM_MB}MB — recommandé: ${REQUIRED_RAM_MB}MB pour $TEAMS équipes"
  else
    ok "RAM suffisante (${TOTAL_RAM_MB}MB disponible, ${REQUIRED_RAM_MB}MB recommandé)"
  fi
fi

# Disk space check (need at least 2GB)
AVAILABLE_DISK_MB=$(df -m . 2>/dev/null | awk 'NR==2{print $4}' || echo 0)
if [ "$AVAILABLE_DISK_MB" -gt 0 ]; then
  if [ "$AVAILABLE_DISK_MB" -lt 2048 ]; then
    warn "Espace disque faible: ${AVAILABLE_DISK_MB}MB — recommandé: 2048MB minimum"
  else
    ok "Espace disque suffisant (${AVAILABLE_DISK_MB}MB disponible)"
  fi
fi

# Port availability check
check_port() {
  if command -v ss &>/dev/null; then
    ss -tlnp 2>/dev/null | grep -q ":$1 " && return 1
  elif command -v netstat &>/dev/null; then
    netstat -tlnp 2>/dev/null | grep -q ":$1 " && return 1
  fi
  return 0
}

PORTS_BUSY=()
# Dashboard
check_port 5000 || PORTS_BUSY+=(5000)
# Team ports
for i in $(seq 1 "$TEAMS"); do
  check_port $((3000 + i)) || PORTS_BUSY+=($((3000 + i)))
  check_port $((4000 + i)) || PORTS_BUSY+=($((4000 + i)))
done

if [ ${#PORTS_BUSY[@]} -gt 0 ]; then
  warn "Ports déjà utilisés: ${PORTS_BUSY[*]} — les conteneurs existants seront remplacés"
else
  ok "Tous les ports nécessaires sont disponibles"
fi

# ─────────────────────────── Validate team count ───────────────────────────

if [ "$TEAMS" -lt 1 ] || [ "$TEAMS" -gt ${#NAMES[@]} ]; then
  fail "Nombre d'équipes entre 1 et ${#NAMES[@]}"
fi

echo ""
echo "⚙️  Génération de docker-compose.yml pour $TEAMS équipe(s)..."
echo ""

# ─────────────────────────── Generate docker-compose.yml ───────────────────────────

FILE="docker-compose.yml"
ADMIN_PWD=$(head -c 100 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 8)

cat > "$FILE" <<EOF
# Auto-generated by setup.sh — $TEAMS equipe(s)
# Toggle "0" / "1" pour activer le branding Nantes@Hack sur tous les services.
x-build-args: &build-args
  VITE_NANTES_HACK: "$NANTES_HACK"

services:
  # Central live dashboard (to project on screen)
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
      args: *build-args
    environment:
      - ADMIN_PASSWORD=$ADMIN_PWD
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/scoreboard"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    mem_limit: 256m
    volumes:
      - dashboard-data:/app/dashboard/data
EOF

# Pre-generate random passwords (5 alphanumeric chars)
declare -a PASSWORDS
for i in $(seq 1 "$TEAMS"); do
  PASSWORDS[$i]=$(head -c 100 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 5)
done

for i in $(seq 1 "$TEAMS"); do
  NAME=${NAMES[$((i - 1))]}
  SITE_PORT=$((3000 + i))
  EXPLOIT_PORT=$((4000 + i))
  TEAM_PWD=${PASSWORDS[$i]}

  cat >> "$FILE" <<EOF

  # ──────────────────────── Team $i ────────────────────────
  site-team${i}:
    build:
      context: .
      dockerfile: Dockerfile.site
      args: *build-args
    environment:
      - TEAM_NAME=$NAME
      - DASHBOARD_URL=http://dashboard:5000
    ports:
      - "${SITE_PORT}:3000"
    depends_on:
      dashboard:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/products"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    mem_limit: 256m

  exploit-team${i}:
    build:
      context: .
      dockerfile: Dockerfile.exploit
      args: *build-args
    environment:
      - TEAM_NAME=$NAME
      - TEAM_PASSWORD=$TEAM_PWD
      - SITE_URL=http://site-team${i}:3000
      - DASHBOARD_URL=http://dashboard:5000
    ports:
      - "${EXPLOIT_PORT}:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    mem_limit: 128m
    volumes:
      - exploit-team${i}-data:/app/exploit-server/data
EOF
done

# ─────────────────────────── Volumes ───────────────────────────

cat >> "$FILE" <<EOF

volumes:
  dashboard-data:
EOF

for i in $(seq 1 "$TEAMS"); do
  cat >> "$FILE" <<EOF
  exploit-team${i}-data:
EOF
done

ok "docker-compose.yml généré"

# ─────────────────────────── Generate credentials files ───────────────────────────

# JSON
CREDS_JSON="credentials.json"
echo "{" > "$CREDS_JSON"
echo "  \"admin_password\": \"$ADMIN_PWD\"," >> "$CREDS_JSON"
echo "  \"dashboard_url\": \"http://localhost:5000\"," >> "$CREDS_JSON"
echo "  \"teams\": [" >> "$CREDS_JSON"
for i in $(seq 1 "$TEAMS"); do
  NAME=${NAMES[$((i - 1))]}
  COMMA=","
  [ "$i" -eq "$TEAMS" ] && COMMA=""
  cat >> "$CREDS_JSON" <<EOF
  {
    "team": $i,
    "name": "$NAME",
    "password": "${PASSWORDS[$i]}",
    "site_url": "http://localhost:$((3000 + i))",
    "exploit_url": "http://localhost:$((4000 + i))"
  }${COMMA}
EOF
done
echo "  ]" >> "$CREDS_JSON"
echo "}" >> "$CREDS_JSON"
ok "credentials.json généré"

# HTML (printable cards)
CREDS_HTML="credentials.html"
cat > "$CREDS_HTML" <<'HTMLHEAD'
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>Identifiants CTF</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: system-ui, sans-serif; background: #f3f4f6; padding: 20px; }
  .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; max-width: 800px; margin: 0 auto; }
  .card {
    border: 2px dashed #9ca3af; border-radius: 12px; padding: 24px;
    background: white; page-break-inside: avoid; text-align: center;
  }
  .card h2 { font-size: 1.5rem; margin-bottom: 12px; color: #1f2937; }
  .card .team-emoji { font-size: 2rem; margin-bottom: 8px; }
  .card .field { margin: 8px 0; font-size: 0.9rem; color: #4b5563; }
  .card .field strong { color: #1f2937; }
  .card .password {
    display: inline-block; margin-top: 8px; padding: 8px 20px;
    background: #fef3c7; border: 2px solid #f59e0b; border-radius: 8px;
    font-family: monospace; font-size: 1.3rem; font-weight: bold; letter-spacing: 2px;
  }
  .scissors { text-align: center; color: #9ca3af; font-size: 0.8rem; margin: 12px 0; }
  @media print {
    body { background: white; padding: 0; }
    .scissors { display: none; }
    .card { border: 2px dashed #ccc; }
  }
</style>
</head>
<body>
<div class="grid">
HTMLHEAD

for i in $(seq 1 "$TEAMS"); do
  NAME=${NAMES[$((i - 1))]}
  cat >> "$CREDS_HTML" <<EOF
  <div class="card">
    <div class="team-emoji">🍌</div>
    <h2>Team $NAME</h2>
    <div class="field"><strong>Site:</strong> http://localhost:$((3000 + i))</div>
    <div class="field"><strong>Exploit Server:</strong> http://localhost:$((4000 + i))</div>
    <div class="field"><strong>Mot de passe:</strong></div>
    <div class="password">${PASSWORDS[$i]}</div>
  </div>
EOF
done

cat >> "$CREDS_HTML" <<'HTMLFOOT'
</div>
</body>
</html>
HTMLFOOT
ok "credentials.html généré (ouvrir dans un navigateur pour imprimer)"

# ─────────────────────────── Summary ───────────────────────────

echo ""
echo "📋 Résumé de la configuration"
echo ""
echo "  Dashboard:  http://localhost:5000"
for i in $(seq 1 "$TEAMS"); do
  echo "  Team $i:     http://localhost:$((3000 + i)) (site)  http://localhost:$((4000 + i)) (exploit)"
done
echo ""
echo "╔══════════════════════════════════════════╗"
echo "║        MOTS DE PASSE DES EQUIPES        ║"
echo "╠══════════════════════════════════════════╣"
for i in $(seq 1 "$TEAMS"); do
  printf "║  %-10s  mdp: %-5s               ║\n" "${NAMES[$((i - 1))]}" "${PASSWORDS[$i]}"
done
echo "╠══════════════════════════════════════════╣"
printf "║  Admin dashboard:  %-20s ║\n" "$ADMIN_PWD"
echo "╚══════════════════════════════════════════╝"

# ─────────────────────────── Deploy ───────────────────────────

if $DEPLOY; then
  echo ""
  echo "🚀 Lancement du déploiement..."
  echo ""
  docker compose up --build -d
  echo ""
  ok "Déploiement terminé !"
  echo ""
  info "En attente que les services soient prêts..."
  sleep 5

  # Quick health check
  ALL_OK=true
  for i in $(seq 1 "$TEAMS"); do
    if ! docker compose ps "site-team${i}" 2>/dev/null | grep -q "running"; then
      warn "site-team${i} ne semble pas démarré"
      ALL_OK=false
    fi
    if ! docker compose ps "exploit-team${i}" 2>/dev/null | grep -q "running"; then
      warn "exploit-team${i} ne semble pas démarré"
      ALL_OK=false
    fi
  done
  if ! docker compose ps dashboard 2>/dev/null | grep -q "running"; then
    warn "dashboard ne semble pas démarré"
    ALL_OK=false
  fi

  if $ALL_OK; then
    echo ""
    ok "Tous les services sont en cours d'exécution !"
  else
    echo ""
    warn "Certains services ne sont pas encore prêts. Vérifiez: docker compose ps"
  fi
else
  echo ""
  echo "Lancez: docker compose up --build -d"
  echo "   ou : ./setup.sh $TEAMS --deploy"
fi

echo ""
