const FLAGS = {
  DATA_EXPOSURE: 'CTF{D3BUG_3NDP01NT_L34K}',
  IDOR: 'CTF{ID0R_PR0FILE_4CC3SS}',
  REFLECTED_XSS: 'CTF{R3FL3CT3D_XSS_S34RCH}',
  SQLI: 'CTF{SQL1_4DM1N_BYP4SS}',
  BUSINESS_LOGIC: 'CTF{N3G4T1V3_CR3D1T_H4CK}',
  JWT_FORGING: 'CTF{F0RG3D_JWT_4DM1N}',
  STORED_XSS: 'CTF{ST0R3D_XSS_R3V13W}',
};

const FLAG_NAMES = {
  [FLAGS.DATA_EXPOSURE]: 'Sensitive Data Exposure',
  [FLAGS.IDOR]: 'IDOR',
  [FLAGS.REFLECTED_XSS]: 'Reflected XSS',
  [FLAGS.SQLI]: 'SQL Injection',
  [FLAGS.BUSINESS_LOGIC]: 'Business Logic',
  [FLAGS.JWT_FORGING]: 'JWT Forging',
  [FLAGS.STORED_XSS]: 'Stored XSS',
};

const ALL_FLAGS = Object.values(FLAGS);

module.exports = { FLAGS, FLAG_NAMES, ALL_FLAGS };
